path: /about
hero:
  particles: true
  title: About Stoplight
  subtitle: Stoplight enables all stakeholders working with APIs to be more productive
  ctas:
    - color: accent
      href: '/careers'
      title: Join Our Team
mission:
  title: Our Mission
  description: We believe in a design-first approach to API development, so we created products that provide a means for design-first development.  Developing good design-first practices will minimize future costs, speed  up your time to market and lead to more consistent, higher quality  microservice and IoT applications.
coreValues:
  title: Our Core Values
  description: At Stoplight, we ground ourselves around three guiding principles that unite us. We do our best work when
    we’re empowered, collaborative, and moving forward with positive intent.
  values:
    - title: Be An Owner
      summary: >-
        When we see an opportunity to make an impact, we seize it.
      icon: 'medal'
      iconStyle:
        '--fa-primary-color': 'gold'
        '--fa-secondary-color': 'gold'
    - title: Build Together
      summary: >-
        We trust in each other to add value and solve problems through teamwork.
      icon: 'hammer'
      iconStyle:
        '--fa-primary-color': 'green'
        '--fa-secondary-color': 'green'
    - title: Practice Mindfulness
      summary: >-
        We seek to understand by listening, inquiring, and responding thoughtfully.
      icon: 'brain'
      iconStyle:
        '--fa-primary-color': 'blue'
        '--fa-secondary-color': 'blue'
careers:
  title: Careers
  image: /images/team/careerdogs.jpg
  description: >-
    The Stoplight team is a talented and creative group (office pups included); united in our passion for creating best in class API tooling.
    We're always looking for enthusiastic, curious, mission-driven individuals to join us as we power the world’s leading API first companies. Think you'd be a good fit?
    Check out our [current open roles](https://stoplight.io/careers)!
socialGood:
  title: Social Good
  image: /images/team/offset-earth-badge.png
  description: >-
      At Stoplight, we believe the positive impact we can make on the world isn't limited to the API space.
      That’s why we work with organizations like [Offset Earth](https://offset.earth/stoplightinc), [Urban Roots](https://urbanrootsatx.org/),
      and [OSMI](https://osmihelp.org/). Check out our [Offset Earth Forest](https://offset.earth/stoplightinc)
      to learn how we offset the carbon footprint of every Stoplight employee and became a climate positive workforce.
team:
  title: Meet The Team
  description: >-
    Headquartered in Austin, Texas, our team hails from across the US and Europe, and is united by our
    passion for APIs. From skeeball champions to rock climbers, tough mudders to restaurateurs, each and
    every member brings their own unique perspectives and experiences to the table. Thinking out of the
    box is our purpose - the weirder the better - and challenging the status quo is our culture.
  image: /images/team/team.jpg
  actionBar:
    ctas:
      - color: accent
        href: '/careers'
        title: Learn More
    enabled: true
    text: Want to join the team? We're hiring!
  members:
    - image: /images/bachi-collin-1-.jpg
      name: Collin Bachi
      role: Devops Engineer
    - image: /images/cassera_headshot.png
      name: Nicholas Cassera
      role: Software Engineer
    - image: /images/chianese_headshot.png
      name: Vincenzo Chianese
      role: Software Engineer
    - image: /images/faust_headshot.png
      name: Scott Faust
      role: Growth
    - image: /images/deborah-garnel-headshot.jpg
      name: Deborah Garnel
      role: SDET
    - image: /images/hilton_headshot.png
      name: William Hilton
      role: Software Engineer
    - image: /images/chelsea-hohmann-headshot.jpg
      name: Chelsea Hohmann
      role: Software Engineer
    - image: /images/jakub-jankowski-headshot.jpg
      name: Jakub Jankowski
      role: Software Engineer
    - image: /images/lott_headshot.png
      name: Chris Lott
      role: Software Engineer
    - image: /images/carol-maciaszek-headshot.png
      name: Karol Maciaszek
      role: Software Engineer
    - image: /images/macleod_headshot.png
      name: Marc MacLeod
      role: Founder & CEO
    - image: /images/mcdonald_headshot.png
      name: Ross McDonald
      role: Customer Success
    - image: /images/chris-miaskowski-headshot.jpg
      name: Chris Miaskowski
      role: Software Engineer
    - image: /images/team/vazha-omanashvili.png
      name: Vazha Omanashvili
      role: Software Engineer
    - image: /images/team/stephen-price.jpg
      name: Stephen Price
      role: Sales Engineer
    - image: /images/pytleski_headshot.png
      name: Thomas Pytleski
      role: Software Engineer
    - image: /images/dave-headshot.jpg
      name: Dave Roberts
      role: Sales Engineering
    - image: /images/tonia-roberts-headshot.jpg
      name: Tonia Roberts
      role: Enterprise Account Executive
    - image: /images/jakub-rozek-headshot.jpg
      name: Jakub Rozek
      role: Software Engineer
    - image: /images/sarah-spear.jpeg
      name: Sarah Spear
      role: Software Engineer
    - image: /images/phil-sturgeon-headshot2.png
      name: Phil Sturgeon
      role: Software Architect
    - image: /images/surratt-headshot.jpg
      name: Kristen Surratt
      role: Customer Advocate
    - image: /images/team/paula-tulis.jpg
      name: Paula Tulis
      role: Software Engineer
    - image: /images/wallach_headshot.png
      name: Robert Wallach
      role: Content & Support
    - image: /images/harrison-yeager-headshot.jpg
      name: Harrison Yeager
      role: Ops
    - image: /images/team/tamina-zaheri.png
      name: Tamina Zaheri
      role: Product Advocate
businesses:
  quotes:
    - author: Evin Callahan
      company: Hudya
      image:
        alt: Hudya
        src: /images/hudya_logo.png
      quote: >-
        Having all the tools to model, test, and document our API in one place,
        and integrating it nicely along the entire CI/CD workflow process has
        been extremely helpful for us.
      role: Cloud Architect
    - author: Josh Flyer
      company: AppointmentPlus
      image:
        alt: AppointmentPlus
        src: /images/appointment_plus_logo.png
      quote: >-
        We really enjoy the modeling feature, helping us define our API before
        even writing code. Also, the way the modeling feature inherits models
        from other Projects. Hubs integrates with OAS files, both partials or
        the entire schema, which is rad.
      role: Lead Developer
    - author: Carlos Lozano
      company: GFT Group
      image:
        alt: GFT Group
        src: /images/gft_group_logo.jpg
      quote: >-
        Stoplight is getting better all the time. Big leap from [Stoplight]
        Classic.
      role: Senior Enterprise Architect
  title: Businesses Love Stoplight
press:
  articles:
    - date: 'October, 2018'
      description: >-
        Software startup raises more than $3M in round led by former Austin
        Ventures bigwig
      href: >-
        https://www.bizjournals.com/austin/news/2018/10/03/software-startup-raises-more-than-3m-in-round-led.html
      image: /images/logo_austin_bj.png
      publication: Austin Business Journal
    - date: 'October, 2018'
      description: Austin startup Stoplight raises more than $3 million.
      href: >-
        https://www.statesman.com/news/20181003/austin-startup-stoplight-raises-more-than-3-million
      image: /images/logo_statesman.png
      publication: Austin-American Statesmen
    - date: 'October, 2018'
      description: 'To Help Developers Get A Grip On APIs, Stoplight Raises $3.25M'
      href: >-
        https://news.crunchbase.com/news/to-help-developers-get-a-grip-on-apis-stoplight-raises-3-25m
      image: /images/logo_crunchbase.png
      publication: crunchbase news
    - date: 'October, 2018'
      description: >-
        Stoplight Lands $3.25M of Seed Funding to Lead Evolution of Enterprise
        API Lifecycle Management
      href: >-
        https://venturebeat.com/2018/10/03/stoplight-lands-3-25m-of-seed-funding-to-lead-evolution-of-enterprise-api-lifecycle-management
      image: /images/logo_venturebeat.png
      publication: VentureBeat
  cta:
    color: grey-darkest
    href: 'https://press.stoplight.io/company'
    title: More Press & Assets
  title: In The Press
collage:
  title: Our Investors
  images:
    - alt: Bill Wood Ventures
      src: /images/bill-wood-logo_trans.png
    - alt: NextGen Venture Partners
      src: /images/logo_next_gen_ventures.png
    - alt: Next Coast Ventures
      src: /images/logo_nextcoast.png
    - alt: Techstars
      src: /images/logo_techstars.png
    - alt: Capital Factory
      src: /images/logo_capitalfactory.png
    - alt: Social Starts
      src: /images/logo_socialstarts.png
meta:
  description: >-
    Find out all you need to know about Stoplight and it's talented and creative
    team; united in their passion for creating best in class API tooling.
  favicon: /images/mark_light_bg.png
  title: Learn About Us | Stoplight
  twitter:
    title: Learn About Us | Stoplight
    username: '@stoplightio'
