hero:
  ctas:
    - submit:
        button:
          color: purple
          href: /demo/
          title: Book a Demo
        formId: a5fb939e-7da2-4a9e-9784-338f92a71e41
        input:
          placeholder: Your business email...
          type: email
      title: Book a Demo
      type: submit
  image:
    alt: Stoplight Enterprise Platform
    src: /images/enterprise/hero.png
  particles: true
  subtitle: >-
    The Stoplight Enterprise Platform increases the consistency, visibility, and
    quality of your internal and external APIs.
  title: API Design Management at Scale
cards:
  cardBottom:
    author: test test
    color: blue
    meta: 'test test test '
    tag: HR
    text: and more text optional
  cardMiddle:
    description: here is a test description. blah blah blah yghjkldcsovodvopj
  cardTop:
    subtitle: Test subtitle
    title: Test title
  hoverable: true
  href: stoplight.io
meta:
  description: >-
    Increase the consistency, visibility, and quality of your internal and
    external APIs with the Stoplight Enterprise Platform.
  favicon: /images/mark_light_bg.png
  image: /images/enterprise/hero.png
  title: Enterprise - API Design Management at Scale | Stoplight
  twitter:
    description: >-
      Increase the consistency, visibility, and quality of your internal and
      external APIs with the Stoplight Enterprise Platform.
    title: Enterprise - API Design Management at Scale | Stoplight
    username: '@stoplightio'
