path: /careers/sr-product-designer
href: 'https://stoplight.careerplug.com/jobs/1006351/apps/new'
title: Senior Product Designer
tags:
  - careers
image: https://images.unsplash.com/photo-1518349619113-03114f06ac3a?ixlib=rb-1.2.1&auto=format&fit=crop&w=800&q=60
actionBar:
  ctas:
    - color: accent
      href: 'https://www.stoplight.com/about'
      title: About us
  enabled: true
  text: Find out more about what it's like to work at Stoplight
subtitle: >-
  FULL TIME • AUSTIN, TX
color: blue
hubspot:
  formId: b1cc69d9-4b4a-4ea4-a199-b9e7ed0b7a09
  portalId: '4892910'
leftContent:
  description: >-

    ### Stoplight is hiring a Senior Product Designer that can take full ownership with end-to-end design. We are growing fast and looking to bring on exceptional team members to make an impact on how software teams build products. This person will thrive within a collaborative, ever-changing environment.

    ### What is Stoplight?


    Stoplight helps organizations design, document, test, collaborate and 
    govern their APIs. We are the first product to effectively cover the entire 
    API development lifecycle.<br><br>Stoplight’s mission is to make any stakeholder 
    working with an API more productive. We work with individual developers to large companies 
    including EA, Spotify, Sendgrid, and many others.


    ### Why are we doing this?


    We created Stoplight because we found existing API solutions tools 
    to be inadequate. After talking with thousands of users and growing 
    to 500+ paying customers, it’s clear there is a massive void for 
    Stoplight to become the must-have workflow solution for any organization 
    looking to streamline their API strategy.


    ### What does it take to be successful in this role?


    - You thrive in a highly collaborative environment

    - You are curious and have a willingness to learn from/teach your colleagues

    - Passionate about user experience

    - You have a constant curiosity to grow your skills beyond the workplace

    - You love boiling complicated problems down to simple solutions


    ### Responsibilities 

    - Design highly usable and delightful user interfaces, experiences, as visuals as part of a software product team; taking ownership of both UX and visual design responsibilities

    - Generate clear ideas, concepts and designs of any form of creative assets from beginning to end

    - Collaborate with engineers, product managers, researchers, data scientist partners to create transformative visuals and easy to use and emotionally engaging interfaces

    - Collaborate closely and provide hands on graphic design support and assets to the development team (layout direction, CSS, images)

    - Manage the quality of design through all phases of the process and the live product

    - Define, codify and establish the standards for high quality visual design on the product

    - Manage the execution of typography, icons, logos, assets and interfaces for multiple platforms

    - Leverage and build creative assets to establish our companies design language system

    - Collaborate with marketing and leadership to ensure a consistent and cohesive brand expression

    - Provide leadership through the interaction and visual design of products and services from end-to-end, across all platforms

    - Staying in the loop and on top of the latest standards, changes, trends in visual design field

    ### Requirements


    - 4+ years of experience with end-to-end visual design background

    - Excellent visual and interaction skills — a master in their field

    - Extensive experience with Sketch, Photoshop, Illustrator, InVision, Figma, etc.

    - The ability to attack all design challenges with energy and enthusiasm for making users’ lives better

    - An amazing portfolio that demonstrates the use of creative and novel solutions to solve complex problems

    - Systems-thinker with the ability to think beyond the pixels and design for offline experiences

    - Experience with marketing and making complex services easily digestible for your audience

    - Experience designing for multiple device types and contexts

    - Defines the design process and can lead others through it. Can accurately scope their work as well as their teammates'

    - Strong communication and stakeholder management skills

    - Demonstrated ability to help a team navigate ambiguity, set vision and strategy for global products

    Plus -  Domain experience in enterprise software tools and software aimed at technical audiences (developers, IT operations, etc.)


    ### Benefits


    Competitive salary. Stock options. Health, medical and dental. 401k.

    ### About 

    Headquartered in Austin, Texas, our team hails from across 
    the US and Europe, and is united by our passion for APIs. 
    From skeeball champions to rock climbers, tough mudders to 
    restaurateurs, each and every member brings their own unique 
    perspectives and experiences to the table. Thinking out of the 
    box is our purpose - the weirder the better - and challenging 
    the status quo is our culture.
meta:
  description: >-
    Stoplight is hiring a Senior Product Designer.
  favicon:
  image:
  title: Senior Product Designer | Stoplight
  twitter:
    description: >-
      Stoplight is hiring a Senior Product Designer.
    image: /images/gartner_cv_2019_rgb.png
    title: Senior Product Designer | Stoplight
    username: '@stoplightio'
