path: /careers/graphic-designer
href: 'https://stoplight.careerplug.com/jobs/1006363/apps/new'
title: Future Opportunity - Graphic Designer
tags:
  - careers
image: https://images.unsplash.com/photo-1523436278115-b135a7a26ad6?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60
actionBar:
  ctas:
    - color: accent
      href: 'https://www.stoplight.com/about'
      title: About us
  enabled: true
  text: Find out more about what it's like to work at Stoplight
subtitle: >-
  FULL TIME • AUSTIN, TX
color: blue
hubspot:
  formId: b1cc69d9-4b4a-4ea4-a199-b9e7ed0b7a09
  portalId: '4892910'
leftContent:
  description: >-

    ### Stoplight is looking for a talented graphic designer to join the team.


    As a graphic designer for Stoplight you would be responsible for creating and maintaining 
    our brand. You will work on the design of the Stoplight website, all marketing and sales design 
    needs, and all branding. You'll work very closely together with almost everyone in Stoplight to 
    make sure we follow good design principles and our branding is clear in everything we do. 
    This means you get a lot of freedom, independence, and responsibilities.


    ### What is Stoplight?


    Stoplight helps organizations design, document, test, collaborate and 
    govern their APIs. We are the first product to effectively cover the entire 
    API development lifecycle.<br><br>Stoplight’s mission is to make any stakeholder 
    working with an API more productive. We work with individual developers to large companies 
    including EA, Spotify, Sendgrid, and many others.


    ### Why are we doing this?


    We created Stoplight because we found existing API solutions tools 
    to be inadequate. After talking with thousands of users and growing 
    to 500+ paying customers, it’s clear there is a massive void for 
    Stoplight to become the must-have workflow solution for any organization 
    looking to streamline their API strategy.


    ### What does it take to be successful in this role?

    - You thrive in a highly collaborative environment

    - You are curious and have a willingness to learn from/teach your colleagues

    - You are passionate about user experience

    - You have a constant curiosity to grow your skills beyond the workplace

    - You love boiling complicated problems down to simple solutions

    ### Responsibilities


    - Set the brand of Stoplight

    - Design a coherent brand image (logo's, icons, colors, typography, etc.)

    - Make updates to the website

    - Design our marketing materials

    - Design our swag (t-shirts, stickers, etc.)

    - Design for special occasions (product releases, events, etc.)

    - Create exciting marketing materials

    - Create printed materials (business cards, banners, brochures)

    - Create web advertisements


    ### Requirements


    - Degree in graphic design or related field, or experience with web design

    - Ability to create anything from quick mockups to pixel-perfect work

    - Ability to create exciting marketing materials

    - Experience with web design and its limitations and possibilities

    - Have an understanding of good UX

    - Experience with HTML / CSS is a plus

    - Illustration experience is a plus

    - Comfortable working very collaboratively on projects, as well as independently


    ### Benefits


    Competitive salary. Stock options. Health, medical and dental. 401k.

    ### About 

    Headquartered in Austin, Texas, our team hails from across 
    the US and Europe, and is united by our passion for APIs. 
    From skeeball champions to rock climbers, tough mudders to 
    restaurateurs, each and every member brings their own unique 
    perspectives and experiences to the table. Thinking out of the 
    box is our purpose - the weirder the better - and challenging 
    the status quo is our culture.
meta:
  description: >-
    Stoplight is hiring a Graphic Designer.
  favicon:
  image:
  title: Graphic Designer | Stoplight
  twitter:
    description: >-
      Stoplight is hiring a Graphic Designer.
    image: /images/gartner_cv_2019_rgb.png
    title: Graphic Designer | Stoplight
    username: '@stoplightio'
