path: /careers/sr-fullstack-javascript-engineer
href: 'https://stoplight.careerplug.com/jobs/1006347/apps/new'
title: Senior Fullstack JavaScript Engineer
tags:
  - careers
image: https://images.unsplash.com/photo-1555099962-4199c345e5dd?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=60
actionBar:
  ctas:
    - color: accent
      href: 'https://www.stoplight.com/about'
      title: About us
  enabled: true
  text: Find out more about what it's like to work at Stoplight
subtitle: >-
  FULL TIME • AUSTIN, TX
color: blue
hubspot:
  formId: b1cc69d9-4b4a-4ea4-a199-b9e7ed0b7a09
  portalId: '4892910'
leftContent:
  description: >-

    ### Stoplight is looking for a senior full-stack engineer with an initial focus on several projects involving our React frontend. We're growing fast looking to bring on exceptional team members to make an impact on how software teams build products.



    ### What is Stoplight?


    Stoplight helps organizations design, document, test, collaborate and 
    govern their APIs. We are the first product to effectively cover the entire 
    API development lifecycle.<br><br>Stoplight’s mission is to make any stakeholder 
    working with an API more productive. We work with individual developers to large companies 
    including EA, Spotify, Sendgrid, and many others.


    ### Why are we doing this?


    We created Stoplight because we found existing API solutions tools 
    to be inadequate. After talking with thousands of users and growing 
    to 500+ paying customers, it’s clear there is a massive void for 
    Stoplight to become the must-have workflow solution for any organization 
    looking to streamline their API strategy.


    ### What does it take to be successful in this role?


    - You consider yourself one of the top React and/or Node.js at your current or past role. Experience with Typescript and GraphQL a plus.

    - You understand how to architect and scale complicated technical problems.

    - You thrive in a highly collaborative environment.

    - You are curious and have a willingness to learn from/teach your colleagues.

    - Passionate about user experience.

    - You have a constant curiosity to grow your skills beyond the workplace.

    - You love boiling complicated problems down to simple solutions.


    ### Benefits


    Competitive salary. Stock options. Health, medical and dental. 401k.

    ### About 

    Headquartered in Austin, Texas, our team hails from across 
    the US and Europe, and is united by our passion for APIs. 
    From skeeball champions to rock climbers, tough mudders to 
    restaurateurs, each and every member brings their own unique 
    perspectives and experiences to the table. Thinking out of the 
    box is our purpose - the weirder the better - and challenging 
    the status quo is our culture.
meta:
  description: >-
    Stoplight is hiring a Senior Fullstack JavaScript Engineer.
  favicon:
  image:
  title: Senior Fullstack JavaScript Engineer | Stoplight
  twitter:
    description: >-
      Stoplight is hiring a Senior Fullstack JavaScript Engineer.
    image: /images/gartner_cv_2019_rgb.png
    title: Senior Fullstack JavaScript Engineer | Stoplight
    username: '@stoplightio'
